services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - server
    mem_limit: 512m
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
networks:
  server:
    external: true
