services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      mem_limit: 700mb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command:
      - sh
      - -c
      - nginx -g 'daemon off;'
    networks:
      - server

networks:
  server:
    external: true

