services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
    mem_limit: 3g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - server

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.3
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LOGSTASH_JAVA_OPTS=-Xms256m -Xmx512m
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline

    networks:
      - server

volumes:
  es_data:

networks:
  server:
    external: true
