services:
  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    container_name: kafka-rest
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_BOOTSTRAP_SERVERS: broker:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
    networks:
      - server
networks:
  server:
    external: true

